#!/usr/bin/ksh
################################################################################
# @author      Anderson Deluiz (Twitter: @AndDeluiz)                           #
# @name        limpaJournalMumps                                               #
# @version     1.0                                                             #
# @date        Nov 24, 2014                                                    #
# @description Limpa arquivo de journaling do Mumps e reinicia o sistema.      #
#                                                                              #
# @usage       limpaJournalMumps                                               #
################################################################################

#---------------------------        INCLUDE       -----------------------------#

#---------------------------     DEBUG OPTIONS    -----------------------------#
# uncomment line(s) to activate debug function
# set -x    # print a trace of simple commands and their arguments
# set -v    # print shell input lines as they are read
# set -n    # read commands but do not execute them

#---------------------------   GLOBAL VARIABLES   -----------------------------#
myName=$(basename $0)
osName=$(uname -s)
myVersion=$(awk '/^# @version/ {print $3}' ${myName})
myHostname=$(hostname)

# Logfile definitions
myLogDir=log/${myName%.*}
myLogFile=${myLogDir}/${myName%.*}-$(date "+%Y%m%d-%H%M%S").log
myLogFilePattern="${myLogDir}/${myName%.*}*.log"
numOfLogFiles=12

# E-mail definitions
cmdMail=/usr/bin/mailx
mailAddress=

# Open M home directory
mumpsHomeDir=/home/msql

# Open M start/stop commands
mumpsStartCmd=${mumpsHomeDir}/mstart
mumpsStopCmd=${mumpsHomeDir}/mstop

#---------------------------       FUNCTIONS      -----------------------------#

#------------------------------------------------------------------------------#
# @function    usage                                                           #
# @description Displays usage of this script and help messages and exit script.#
#                                                                              #
# @usage       usage                                                           #
# @in          none                                                            #
# @return      none                                                            #
# @return-code                                                                 #
#              none                                                            #
# @exit-code                                                                   #
#              255 - normal exit code                                          #
#------------------------------------------------------------------------------#
usage()
{
   cat << _EOF_

${myName} version ${myVersion}

   Purpose
   =======
   Limpa arquivo de journaling do Mumps e reinicia o sistema Mumps.

   Syntax
   ======
   ${myName} [-h | --help]

_EOF_
   exit 255
}

#------------------------------------------------------------------------------#
# @function    parse                                                           #
# @description Parses provided arguments.                                      #
#                                                                              #
# @usage       parse <arguments>                                               #
# @in          All arguments provided from command line for execution.         #
# @return      none                                                            #
# @return-code                                                                 #
#              none                                                            #
# @exit-code                                                                   #
#              none                                                            #
#------------------------------------------------------------------------------#
parse()
{
   while [ $# -ne 0 ]
   do
      case $1 in
         '--help'|'-h')
            usage
            ;;
         *)
            usage
            ;;
      esac
   done

   return 0
}  

#------------------------------------------------------------------------------#
# @function    mumpsStop                                                       #
# @description Stop Open M(umps)                                               #
#                                                                              #
# @usage       mumpsStop                                                       #
# @in          none                                                            #
# @return      none                                                            #
# @return-code                                                                 #
#              0 - Open M stopped successfully                                 #
#              1 - Open M isn't running                                        #
#              2 - Open M didn't stop successfully                             #
# @exit-code                                                                   #
#              none                                                            #
#------------------------------------------------------------------------------#
mumpsStop()
{
   if checkMumpsRunning
   then
      ${mumpsStopCmd} << _EOF_
No
No
Yes
_EOF_

   else
      echo "ERROR: Open M is not running! Aborting..."
      return 1
   fi

   if ! checkMumpsRunning
   then
      echo "INFO: Open M stopped successfully!"
      return 0
   else
      echo "ERROR: Open M didn't stop successfully! Check previous messages for additional information."
      return 2
   fi
}  

#------------------------------------------------------------------------------#
# @function    mumpsStart                                                      #
# @description Start Open M(umps)                                              #
#                                                                              #
# @usage       mumpsStop                                                       #
# @in          none                                                            #
# @return      none                                                            #
# @return-code                                                                 #
#              0 - Open M started successfully                                 #
#              1 - Open M already running                                      #
#              2 - Open M didn't start successfully                            #
# @exit-code                                                                   #
#              none                                                            #
#------------------------------------------------------------------------------#
mumpsStart()
{
   if ! checkMumpsRunning
   then
      ${mumpsStartCmd} << _EOF_
Yes
No
 
Yes
Yes
_EOF_

   else
      echo "ERROR: Open M is already running! Aborting..."
      return 1
   fi

   if checkMumpsRunning
   then
      echo "INFO: Open M started successfully! PID = ${mumpsProcess}"
      return 0
   else
      echo "ERROR: Open M didn't start successfully! Check previous messages for additional information."
      return 2
   fi
}  

#------------------------------------------------------------------------------#
# @function    checkMumpsRunning                                               #
# @description Check if Open M(umps) is running.                               #
#              Codigo extraido do script mstop, parte do produto Open M.       #
#                                                                              #
# @usage       checkMumpsRunning                                               #
# @in          none                                                            #
# @return      none                                                            #
# @return-code 0 - Open M is running                                           #
#              1 - Open M is NOT running                                       #
# @exit-code                                                                   #
#              none                                                            #
#------------------------------------------------------------------------------#
checkMumpsRunning()
{
   if [ ! "$(ps -ef | awk '/[ \t]m(sqlm|ux)([ \t]|$)/ {print}')" ]
   then
      # Open M isn't running
      return 1
   fi
   mumpsProcess=$(ps -ef | awk '/[ \t]m(sqlm|ux)([ \t]|$)/ {print}')
   return 0
}  

#---------------------------     MAIN SECTION     -----------------------------#

# Redirect stdin/stderr to $myLogfile
exec > ${myLogFile} 2>&1

mumpsStop
mumpsStart
 
${cmdMail} -s "[${myName}] Log de execucao" ${mailAddress} < ${myLogFile}

exit
